// Level packs. Levels are plain ASCII grids — see LEVELS.md for the format.
// "Moonside" is the new campaign (reach the portal). "Classic 2021" is the
// original Eloquent-JS-era level set, ported verbatim (collect every coin).

export const PACKS = [
  {
    id: 'moonside',
    name: 'Moonside',
    levels: [
      {
        name: "First Light",
        goal: 'exit',
        rows: [
          "                                                ",
          "                                                ",
          "                                                ",
          "                                                ",
          "                                                ",
          "                                                ",
          "                                                ",
          "                                      o         ",
          "                            o        xxxx       ",
          "                  o        xxxx                 ",
          "         o       xxxx                        E  ",
          "  @            xx                          xxxxx",
          "xxxxxxxxxxxxxxxxx    o                          ",
          "xxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxx",
          "xxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxx",
          "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        ],
      },
      {
        name: "Bounce",
        goal: 'exit',
        rows: [
          "                                            ",
          "                                            ",
          "                                            ",
          "                                            ",
          "                                            ",
          "                                            ",
          "                                            ",
          "                                            ",
          "                                            ",
          "                                            ",
          "                        o                   ",
          "            o           x                   ",
          "            x           x            o  E   ",
          "            x           x           xxxxxxxx",
          "            x           x    o      xxxxxxxx",
          "            x o         x  -----    xxxxxxxx",
          "            x           x           xxxxxxxx",
          "            x   o       x           xxxxxxxx",
          "  @      ^  x        ^  x        ^  xxxxxxxx",
          "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        ],
      },
      {
        name: "Thin Air",
        goal: 'exit',
        rows: [
          "                                                    ",
          "                                                    ",
          "                                                    ",
          "                                                    ",
          "                                                    ",
          "            o                                       ",
          "   ----   ----                                      ",
          "                                                    ",
          "        o      o                                E   ",
          "   ----      ----                             xxxxxx",
          "                              o     o     o   xxxxxx",
          "                                              xxxxxx",
          "  @  x                   ~                    xxxxxx",
          "xxxxxx                                        xxxxxx",
          "xxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx",
          "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        ],
      },
      {
        name: "Night Patrol",
        goal: 'exit',
        rows: [
          "                                                    ",
          "                                                    ",
          "                                                    ",
          "                                                    ",
          "                                            E       ",
          "                                          xxxxxx    ",
          "                              o  e                  ",
          "                            xxxxxxxxx               ",
          "                                                    ",
          "              o   e   o                             ",
          "            xxxxxxxxxxxx                            ",
          "                                                    ",
          "   @              e              e                  ",
          "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         ",
          "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    o    ",
          "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        ],
      },
      {
        name: "Lock and Key",
        goal: 'exit',
        rows: [
          "                                                      ",
          "                                                      ",
          "                                                      ",
          "                                                      ",
          "                                                      ",
          "     o                                                ",
          "   xxxxx                                              ",
          "                                                      ",
          "     k                                                ",
          "   xxxxx                        o                     ",
          "                              xxxxx                   ",
          "        o                              D              ",
          "      xxxxx                            D   E          ",
          "                  o                    Dxxxxxxx       ",
          "  @             xxxxx                  Dxxxxxxx   o   ",
          "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        ],
      },
      {
        name: "Ember Rain",
        goal: 'exit',
        rows: [
          "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          "     v      v      v      v      v             v      v     ",
          "                                                            ",
          "                                                            ",
          "                                                            ",
          "                                                            ",
          "                                                            ",
          "                                                            ",
          "                               |                            ",
          "                                                            ",
          "                                                            ",
          "                                            o               ",
          "  @          o        o  *          o   x  =   x    o    E  ",
          "xxxxxxxx  xxxxxxxx  xxxxxxxxxxx  xxxxxx xxxxxxxx  xxxxxxxxxx",
          "xxxxxxxx!!xxxxxxxx!!xxxxxxxxxxx!!xxxxxx!xxxxxxxx!!xxxxxxxxxx",
          "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        ],
      },
      {
        name: "The Lift",
        goal: 'exit',
        rows: [
          "                                    ",
          "  E                                 ",
          "xxxxxx                              ",
          "       xxxx                         ",
          "                                    ",
          "                                    ",
          "                                    ",
          "         H                          ",
          "               o    o               ",
          "             xxxxxxxxxxx            ",
          "                              xxx   ",
          "                          o         ",
          "                         xxxx       ",
          "                                    ",
          "        xxxx                        ",
          "                                    ",
          "                                    ",
          "                                    ",
          "         o                     H    ",
          "        ----                        ",
          "                                    ",
          "    o                               ",
          "  xxxxx                             ",
          "                                    ",
          "                                    ",
          "  @                         o       ",
          "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        ],
      },
      {
        name: "Emberfall",
        goal: 'exit',
        rows: [
          "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                     ",
          "      v      v      v                                                               ",
          "                                                                                    ",
          "                                                                                    ",
          "                                                                             xxxxxxx",
          "                                                                              D     ",
          "                                        |                                  o  D  E  ",
          "                                                                          xxxxxxxxxx",
          "                                                                                    ",
          "                                                                  k                 ",
          "                                                               xxxxxxx              ",
          "                                                                                    ",
          "                                                                            o       ",
          "                                                                         xxxxxxx    ",
          "                                                                                    ",
          "                                                                                    ",
          "                                                                                    ",
          "                                    o       o     o                                 ",
          "                                                                                    ",
          "                         x    ~                         x                           ",
          "  @     o   e   o e    * x                              x *    e    o            ^  ",
          "xxxxxxxxxxxxxxxxxxxxxxxxxx                              xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          "xxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          "xxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          "xxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        ],
      },
    ],
  },
  {
    id: 'classic',
    name: 'Classic 2021',
    levels: [
      {
        name: "Collect!",
        goal: 'coins',
        rows: [
          "                                                                                ",
          "                                                                                ",
          "  vv   xxx xxxx x   x   xxx xxx xxxxx     xxx xxxx x x   x xxxx                 ",
          "       x   x  x x   x   x   x     x       x   x  x x xx  x x                    ",
          "       x   x  x x   x   xxx x     x       x   x  x x x x x xxxx                 ",
          "       x   x  x x   x   x   x     x       x   x  x x x  xx    x                 ",
          "       xxx xxxx xxx xxx xxx xxx   x       xxx xxxx x x   x xxxx                 ",
          "                                                                                ",
          "                                                                                ",
          "                                                                                ",
          "                                                                                ",
          "                                                                                ",
          "                                                                                ",
          "                                                                                ",
          "  xx                 o                         o                          o     ",
          "  x                                                                             ",
          "  x  @                                                                          ",
          "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          "                                                                                ",
          "                                                                                ",
          "                                                                                ",
          "                                                                                ",
          "                                                                                ",
          "                                                                                ",
        ],
      },
      {
        name: "First Steps",
        goal: 'coins',
        rows: [
          "                                                                                ",
          "              vv                                                                ",
          "                                                                                ",
          "                                                                                ",
          "                                                                                ",
          "                                                                                ",
          "                                                                  xxx           ",
          "                                                   xx      xx    xx!xx          ",
          "                                    o o      xx                  x!!!x          ",
          "                                                                 xx!xx          ",
          "                                   xxxxx                          xvx           ",
          "                                                                            xx  ",
          "  xx                                      o o                                x  ",
          "  x                     o                                                    x  ",
          "  x                                      xxxxx                             o x  ",
          "  x          xxxx       o                                                    x  ",
          "  x  @       x  x                                                xxxxx       x  ",
          "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
          "                              x   x                  x     x                    ",
          "                              x!!!x                  x!!!!!x                    ",
          "                              x!!!x                  x!!!!!x                    ",
          "                              xxxxx                  xxxxxxx                    ",
          "                                                                                ",
          "                                                                                ",
        ],
      },
      {
        name: "The Descent",
        goal: 'coins',
        rows: [
          "                                      x!!x                        xxxxxxx                                    x!x  ",
          "                                      x!!x                     xxxx     xxxx                                 x!x  ",
          "                                      x!!xxxxxxxxxx           xx           xx                                x!x  ",
          "                                      xx!!!!!!!!!!xx         xx             xx                               x!x  ",
          "                                       xxxxxxxxxx!!x         x                                    o   o   o  x!x  ",
          "                                                xx!x         x     o   o                                    xx!x  ",
          "                                                 x!x         x                                xxxxxxxxxxxxxxx!!x  ",
          "                                                 xvx         x     x   x                        !!!!!!!!!!!!!!xx  ",
          "                                                             xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
          "                                                              xx!!!!!!!!!!!xx            v                        ",
          "                                                               xxxx!!!!!xxxx                                      ",
          "                                               x     x            xxxxxxx        xxx         xxx                  ",
          "                                               x     x                           x x         x x                  ",
          "                                               x     x                             x         x                    ",
          "                                               x     x                             xx        x                    ",
          "                                               xx    x                             x         x                    ",
          "                                               x     x      o  o     x   x         x         x                    ",
          "               xxxxxxx        xxx   xxx        x     x               x   x         x         x                    ",
          "              xx     xx         x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
          "             xx       xx        x o x          x    xx               x   x   x               x                    ",
          "     @       x         x        x   x          x     x               x   x   x               x                    ",
          "    xxx      x         x        x   x          x     x               x   xxxxx   xxxxxx      x                    ",
          "    x x      x         x       xx o xx         x     x               x     o     x x         x                    ",
          "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
          "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
          "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !                    xx     xx                     ",
          "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
          "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
          "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
          "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  ",
        ],
      },
      {
        name: "The Gauntlet",
        goal: 'coins',
        rows: [
          "                                                                                                              ",
          "                                                                                                              ",
          "                                                                                                              ",
          "                                                                                                              ",
          "                                                                                                              ",
          "                                        o                                                                     ",
          "                                                                                                              ",
          "                                        x                                                                     ",
          "                                        x                                                                     ",
          "                                        x                                                                     ",
          "                                        x                                                                     ",
          "                                       xxx                                                                    ",
          "                                       x x                 !!!        !!!  xxx                                ",
          "                                       x x                 !x!        !x!                                     ",
          "                                     xxx xxx                x          x                                      ",
          "                                      x   x                 x   oooo   x       xxx                            ",
          "                                      x   x                 x          x      x!!!x                           ",
          "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
          "                                     xx   xx      x   x      x                                                ",
          "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
          "                                      x   x           x                    x!!!x                              ",
          "                                      x   x           x                     xxx                               ",
          "                                     xx   xx          x                                                       ",
          "                                      x   x= = = =    x            xxx                                        ",
          "                                      x   x           x           x!!!x                                       ",
          "                                      x   x    = = = =x     o      xxx       xxx                              ",
          "                                     xx   xx          x                     x!!!x                             ",
          "                              o   o   x   x           x     x                xxv        xxx                   ",
          "                                      x   x           x              x                 x!!!x                  ",
          "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
          "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
          "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
          "                             xx           xx                                         xxx                      ",
          "  xxx                         x     x     x                                         x!!!x                xxx  ",
          "  x x                         x    xxx    x                                          xxx                 x x  ",
          "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
          "  x                           x           x                              x   x                             x  ",
          "  x                           xx          x                              x x x                             x  ",
          "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
          "  x                xxx             o o    x                              x         xxx                     x  ",
          "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
          "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
          "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
          "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
          "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
          "                                                                                                              ",
          "                                                                                                              ",
        ],
      },
      {
        name: "Coin Vault",
        goal: 'coins',
        rows: [
          "                                                                                                  xxx x       ",
          "                                                                                                      x       ",
          "                                                                                                  xxxxx       ",
          "                                                                                                  x           ",
          "                                                                                                  x xxx       ",
          "                          o                                                                       x x x       ",
          "                                                                                             o o oxxx x       ",
          "                   xxx                                                                                x       ",
          "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
          "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
          "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
          "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
          "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
          "                                                                                                              ",
          "          o              xxx                              xx                                                  ",
          "                                                                                                              ",
          "                                                                                                              ",
          "                                                      xx                                                      ",
          "                   xxx         xxx                                                                            ",
          "                                                                                                              ",
          "                          o                                                     x      x                      ",
          "                                                          xx     xx                                           ",
          "             xxx         xxx         xxx                                 x                  x                 ",
          "                                                                                                              ",
          "                                                                 ||                                           ",
          "  xxxxxxxxxxx                                                                                                 ",
          "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
          "  x         x   x       x   x       x   x                 ||                  x     x                         ",
          "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
          "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
          "        x=                  =                =x   x                     xxx                                   ",
          "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
          "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          "                                                                                                              ",
        ],
      },
    ],
  },
];
